<?php $productItem = Mage::getModel('sales/quote_item')->getCollection(); ?>
<?php $grandTotal = Mage::getModel('sales/quote')->getCollection();
      $grandTotal = $grandTotal->getFirstItem();
?>
<?php $addressData = Mage::getModel('cart/address')->getCollection()->getData();?>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Responsive Checkout Form</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- <link rel="stylesheet" href="styles.css"> -->
</head>
<body>
<h2>Checkout Form</h2>
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="/action_page.php">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" placeholder="Faraz">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email" placeholder="codewithfaraz@example.com">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="Mira Bhayandar Road">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="Mumbai">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="MH">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="400001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="Faraz">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="December">
            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2027">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="123">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Continue to checkout" class="btn">
      </form>
    </div>
  </div>
  <div class="col-25">
    <div class="container">
      <h4>Cart <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b>4</b></span></h4>
      <?php foreach ($productItem->getData() as $product) { ?>
      <p><a href="#"><?php echo $product->getProductId(); ?></a> <span class="price"><?php echo $product->getPrice(); ?></span></p>
      <?php } ?>
      <!-- <p><a href="#">Item 2</a> <span class="price">$95</span></p>
      <p><a href="#">Item 3</a> <span class="price">$100</span></p>
      <p><a href="#">Item 4</a> <span class="price">$50</span></p> -->
      <hr>
      <p>Total <span class="price" style="color:black"><b><?php echo $grandTotal->getGrandTotal()?></b></span></p>
    </div>
  </div>

  <div>
  <div style="margin-left:40px" class="address-show">
<?php if(!empty($addressData)):?>
<?php foreach ($addressData as $addValue):?>
<div id="asdasdasdasd" class="address-cards" data-json='{"customer":"<?php echo $addValue->getCustomerId();?>","billing_address":"<?php echo $addValue->getBillingAddress();?>","billing_city":"<?php echo $addValue->getBillingCity();?>","billing_country":"<?php echo $addValue->getBillingCountry();?>"}'>
    <p>Address :<?php echo $addValue->getCustomerId()?></p>
    <p>Address :<?php echo $addValue->getBillingAddress()?></p>
    <p>City : <?php echo $addValue->getBillingCity()?></p>
    <p>Country :<?php echo $addValue->getBillingCountry()?></p>
    <p>ZipCode :<?php echo $addValue->getBillingZip()?></p>
    <p>Phone No:<?php echo $addValue->getBillingPhone()?></p>
</div>

<?php endforeach; ?>
<?php endif; ?>
</div>
  <script type="text/javascript">
    $('.address-cards').each((i,e)=>{
        console.log($(e).attr('data-json'))
        $(e).click(()=>{
            var _data = JSON.parse($(e).attr('data-json'))
            for (var key in _data) {
                if (_data.hasOwnProperty(key)) {
                    $('#'+key).val(_data[key]);
                }
            }
            // $('#billing_address').val(_data.billing_address);
            // $('#billing_city').val(_data.billing_city);
            // $('#billing_country').val(_data.billing_country);
        });
    })
</script>
  </div>
</div>
</body>
</html>